# Site
title:              Justine Rae Cruz
bio:                'Computer Science student at California State University, Long Beach. Passionate about combining computers and creativity.'
description:        "Computer Science student passionate about combining computers and creativity."
reading_time:       false
words_per_minute:   200
logo:               'assets/img/logo.png'
background:         'assets/img/simple.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://jaerlcruz.github.io
url:                http://localhost:4000

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            false
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
#disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              jaeraelcruz@gmail.com
#twitter:            username
#facebook:           username
github-url:         jaerlcruz
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          justine-rae-cruz-27025026a
#xing:              username
instagram:          justiine.rae
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
